# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Spreadsheet-WriteExcel-Simple
version:      1.04
version_from: Simple.pm
installdirs:  site
requires:
    IO::Scalar:                    1.126
    Spreadsheet::WriteExcel:       0.31
    Test::More:                    0.04

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
